# Generated by Django 5.1.7 on 2026-01-27 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripleLockVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocr_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ocr_enrollment",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "ocr_college",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ocr_verified", models.BooleanField(default=False)),
                ("ocr_verified_at", models.DateTimeField(blank=True, null=True)),
                ("aadhaar_number_encrypted", models.BinaryField(blank=True, null=True)),
                (
                    "aadhaar_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("aadhaar_address", models.TextField(blank=True, null=True)),
                ("aadhaar_dob", models.DateField(blank=True, null=True)),
                ("aadhaar_verified", models.BooleanField(default=False)),
                (
                    "aadhaar_match_score",
                    models.FloatField(
                        blank=True,
                        help_text="Fuzzy match score between OCR name and Aadhaar name (0-100)",
                        null=True,
                    ),
                ),
                ("aadhaar_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "aadhaar_request_id",
                    models.CharField(
                        blank=True,
                        help_text="API Setu request ID for OTP verification",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("upi_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "upi_payer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("upi_verified", models.BooleanField(default=False)),
                (
                    "upi_match_score",
                    models.FloatField(
                        blank=True,
                        help_text="Fuzzy match score between Aadhaar name and UPI payer name (0-100)",
                        null=True,
                    ),
                ),
                ("upi_verified_at", models.DateTimeField(blank=True, null=True)),
                ("refund_initiated", models.BooleanField(default=False)),
                ("refund_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "refund_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING_OCR", "Pending OCR"),
                            ("PENDING_AADHAAR", "Pending Aadhaar"),
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("VERIFIED", "Fully Verified"),
                            ("FAILED", "Verification Failed"),
                        ],
                        default="PENDING_OCR",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when all three verifications completed",
                        null=True,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for verification failure",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or comments", null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triple_lock",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Triple-Lock Verification",
                "verbose_name_plural": "Triple-Lock Verifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
