# Generated by Django 5.1.7 on 2026-01-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identity_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash of student details to prevent duplicate registrations",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
