# Generated by Django 5.1.7 on 2026-01-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_identity_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="selfie_image",
            field=models.ImageField(
                blank=True,
                help_text="Captured video selfie for admin review",
                null=True,
                upload_to="student_selfies/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("VERIFIED", "Verified"),
                    ("REVIEW", "Under Review"),
                    ("REJECTED", "Rejected"),
                ],
                default="REVIEW",
                help_text="Current verification status of the student",
                max_length=20,
            ),
        ),
    ]
