# Generated by Django 5.1.7 on 2026-01-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_selfie_image_alter_user_verification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Student's 10-digit phone number",
                max_length=10,
                null=True,
            ),
        ),
    ]
