# Generated by Django 5.1.7 on 2026-01-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(
                blank=True, help_text="Student's address from Aadhaar", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="Student's date of birth from Aadhaar", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="upi_id",
            field=models.CharField(
                blank=True,
                help_text="Student's UPI ID for financial verification",
                max_length=255,
                null=True,
            ),
        ),
    ]
